### ISSUE TITLE
Configure error

### ISSUE THREAD

**Issue by j-joshua** [USNavalResearchLaboratory/norm#1]
Fresh install.  Already installed protolib.

[xxx@localhost norm]$ ./waf configure
Cannot read the folder '/home/xxx/norm/protolib'

**Comment by bebopagogo** [comment]
Hi j-joshua,

Did you place the "protolib" source tree (or a symbolic link to it) as a subdirectory of the norm source directory?    When we build NORM source code tarballs, we include a copy of the protolib source tree as part of the distribution.  Now that we have these on GitHub, we may need to do things a little differently.  E.g., update the build system to check for a protolib installation if it is not embedded in the NORM source tree.   

I also hope to establish a mailing list somewhere or other forum to complement the GitHub repository here. 

If the the above suggestion resolved your issue, please let me know.  best regards.

**Comment by j-joshua** [comment]
Hi,

Creating a softlink to protolib was helpful.  I'll follow up with some other build issues.

Thanks.
