### ISSUE TITLE
PROTO_ADDR_BROADCAST not declared

### ISSUE THREAD

**Issue by scij** [USNavalResearchLaboratory/norm#12]
When trying to build NORM from the latest commit (norm and Protolib) I am getting this error:

`../src/common/normSession.cpp:5110:20: error: use of undeclared identifier 'PROTO_ADDR_BROADCAST'
        etherDst = PROTO_ADDR_BROADCAST;
`
And yes, there is no such definition in the source code.
I re-ran `waf configure --build-java` but no changes. 
My system macOS 10.15.5 with the latest Xcode installed.

**Comment by bebopagogo** [comment]
I just pushed the accompanying protolib update that I overlooked doing.  Sorry for the inconvenience.    I think a "cd norm; git pull" should suffice to get the update, but you _may_ also need to do a "git submodule update" within the the 'norm' directory to pull the updated protolib submodulate into your norm tree

**Comment by scij** [comment]
Wow - that was quick. Tks so much.
And yes, git submodule update was necessary.
