### ISSUE TITLE
New release with cmake

### ISSUE THREAD

**Issue by mjvankampen** [USNavalResearchLaboratory/norm#19]
Hi, I'm trying to get norm into conan to make it easier to consume. For that the cmake stuff helps a lot, thanks for letting that in. I would like to now consume norm in conan, but there is a strong preference for an official release.

Of course the previous release did not have cmake in there so to make this work I was wondering if another release would be possible?

Cheers!

Oh and a (possible) release is pending green build in conan, maybe I still have to do some cmake fixes https://github.com/conan-io/conan-center-index/pull/4299

**Comment by mjvankampen** [comment]
Ok all green in conan which means cmake works in all kinds of flavours on mac, windows and linux.

**Comment by bebopagogo** [comment]
OK - I working a 1.5.9 release for this. I am making sure the current protolib master works without issue.  I also have some updates to the experimental (but getting close to ready for broader use) NormSocket API extension.  FYI - I hope to refactor the ZMQ norm_engine at some point to use this NormSocket code as it will enable relatively easy broader support for a wider range of socket types.  It also provides a connection-oriented paradigm like TCP for both unicast and multicast where the server can transmit on a multicast group while each client has its own unicast NORM back channel to the server.  I think that will be useful for ZMQ pub/sub where the server can keep track of the clients ...

**Comment by bebopagogo** [comment]
I published the 1.5.9 release that should satisfy this issue.

**Comment by mjvankampen** [comment]
Thank you very much!
