### ISSUE TITLE
404 page on project site

### ISSUE THREAD

**Issue by chenrui333** [USNavalResearchLaboratory/norm#20]
👋  just a reminder [the site](https://www.nrl.navy.mil/itd/ncs/products/norm) is currently showing 404 page. Thanks!

![image](https://user-images.githubusercontent.com/1580956/106375725-9c93b900-635c-11eb-86a0-bf5bad22bff0.png)

**Comment by bebopagogo** [comment]
Yes - thank you.  We have meetings scheduled this week to see if they will restore those web pages.  Other wise, I will be updating documentation as needed.

**Comment by weston-nrl** [comment]
This link now redirects to the new NORM webpage, and I have also updated the repo link to the new URL.
