### ISSUE TITLE
norm 1.5.9 python binding of setRxPortReuse session's method seems not to work

### ISSUE THREAD

**Issue by urluberluneuf** [USNavalResearchLaboratory/norm#53]
The call of the setRxPortReuse with one boolean argument works with standard C++ lib but not with python: i tried what follows with python 2.7.18 interpreter:
>>> import pynorm
>>> instance = pynorm.Instance()
>>> session = instance.createSession("224.1.2.3", 6003)
>>> session.setRxPortReuse(True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pynorm/session.py", line 48, in setRxPortReuse
    libnorm.NormSetRxPortReuse(self, enable, bindToSessionAddr)
TypeError: this function takes at least 5 arguments (3 given)

**Comment by bebopagogo** [comment]
I think I have addressed this and brought the pynorm code for this up to date with the NORM API
