### ISSUE TITLE
norm 1.5.9 fatal error with the python binding of session's method fileEnqueue

### ISSUE THREAD

**Issue by urluberluneuf** [USNavalResearchLaboratory/norm#54]
On python 2.7.18, with the interpreter, we use the same commands as the ones in the normFileSend.py example:
>>> import pynorm
>>> instance = pynorm.Instance()
>>> session = instance.createSession("224.1.2.3", 6003)
>>> session.setTxRate(256e6)
>>> from random import randint
>>> session.startSender(randint(0, 1000), 1024**2, 1400, 64, 16)
>>> session.fileEnqueue("/home/titi/Documents/NORM/norm-1.5.9/VERSION.TXT", "VERSION.TXT")
Proto Fatal: NormObject::Open() error: object size exceeds FEC blocking and segmentation parameter capability
Proto Fatal: NormFileObject::Open() send object open error
Proto Fatal: NormSession::QueueTxFile() file open error
<pynorm.object.Object object at 0x7fe01b210d10>

**Comment by bebopagogo** [comment]
I just pushed a commit that should fix this.  The "pynorm" code needed some updates to be compatible with Python 3.  I also tweaked the normFileSend.py, normFileRecv.py, and normMgr.py examples to work with Python 3.    I _think_ I have all in order now, but may have missed some detail.

Sorry for the  slow response on getting around to fixing this.
