### ISSUE TITLE
Suggestion: Make pynorm work with Python3

### ISSUE THREAD

**Issue by honglei** [USNavalResearchLaboratory/norm#59]
As https://www.python.org/doc/sunset-python-2/ , hope  for supporting python3

**Comment by honglei** [comment]
function `cmp`  in session.py/object.py `map` in logparser.py should be replaced in Python3.

Try [python-future](https://github.com/PythonCharmers/python-future)

**Comment by bebopagogo** [comment]
@honglei - I will investigate your suggestions here.  On my system, the current pynorm code from the GitHub repo is working with Python 3.8.  I committed some updates a few weeks ago that seem to address that.  I understand that the cmp function is deprecated.  I need to look at the logparser code separately.

**Comment by honglei** [comment]
"On average, the share of Python 2 users decreases by 5 percentage points each year, and now only 5 developers out of 100 use it."
 https://lp.jetbrains.com/python-developers-survey-2021/#PythonVersions 
 https://www.python.org/doc/sunset-python-2/
