### ISSUE TITLE
Error when interface is not working

### ISSUE THREAD

**Issue by RocketRider** [USNavalResearchLaboratory/norm#6]
When I use NORM on Android over an WiFi and the connection goes down(not disabling the interface) I see the following error in the log, but I don't get any event to handle the issue:

> 2020-01-29 12:58:01.749 ? W/protolib: NormSession::SendMessage() sendto(224.1.2.3/4102) warning: Invalid argument
> 2020-01-29 12:58:01.752 ? E/protolib: ProtoSocket::SendTo() sendto() error: Invalid argument

The error is shown in an endless loop and I can't handle it. Is there any way to determine if NORM can send the data correctly?

**Comment by bebopagogo** [comment]
I will take a look at that.  Are you using a WiFi access point and moving out of range or using an ad hoc WiFi net?

**Comment by RocketRider** [comment]
I am using an WiFi access point. And I am just powering off the access point for this test.

**Comment by bebopagogo** [comment]
I am on travel this week so it will be a few days before I can set up a similar test.  If you could set the NORM debug level and logging to capture some debug output, I could possibly see what type of error message (likely a socket error message) is produced for that condition and determine the best strategy for handling it.  Most of our own testing over Wifi has been in ad hoc mode.  

So, it sound like you would benefit from getting a notification when your access point connect is lost?   At the moment, NORM keeps trying to send packets hoping that any sendto() error will go away … it is possible that a NORM API notification could be issued when that occurs … The key is being able to discern between an error that is a single occurrence vs. a more significant event.

**Comment by RocketRider** [comment]
I am using the Loglevel 7, //PL_MAX, and I don't get any more info from NORM.
In the log I can see the messages from the OS, like:

> 2020-02-19 10:14:06.393 ? D/NetworkMonitor/NetworkAgentInfo [WIFI () - 610]: Disconnected

But NORM is not showing anything.

Norm is printing these stats sometime after the disconnect:
> 2020-02-19 10:14:12.129 ? I/protolib: NormSenderNode::OnActivityTimeout() node>175843434 for sender>2681601
> 2020-02-19 10:14:12.766 ? I/protolib: REPORT time>09:14:12.766783 node>175843434 ***************************************
> 2020-02-19 10:14:12.767 ? I/protolib: Local status:
> 2020-02-19 10:14:12.767 ? I/protolib:    txRate>   64.000 kbps sentRate>    0.000 grtt>0.228400
> 2020-02-19 10:14:12.767 ? I/protolib: Remote sender>2681601 grtt>0.422500 sec loss>0.000000
> 2020-02-19 10:14:12.767 ? I/protolib:    rxRate>    0.000 kbps rx_goodput>    0.000 kbps
> 2020-02-19 10:14:12.767 ? I/protolib:    rxObjects> completed>1 pending>0 failed>0
> 2020-02-19 10:14:12.767 ? I/protolib:    fecBufferUsage> current>0 peak>0 overuns>0
> 2020-02-19 10:14:12.767 ? I/protolib:    strBufferUsage> current>0 peak>0 overuns>0
> 2020-02-19 10:14:12.767 ? I/protolib:    resyncs>0 nacks>0 suppressed>0
> 2020-02-19 10:14:12.767 ? I/protolib: ***************************************************************************
> 2020-02-19 10:14:13.263 ? D/io_stats: !@ 179,0 r 82125 4717596 w 150508 4729104 d 11929 24813356 f 37991 40392 iot 165088 147220 th 51200 0 0 pt 0 inp 0 0 47193.862

And a short time after that, it runns into the endless loop of:

> 2020-02-19 10:14:27.635 ? E/protolib: ProtoSocket::SendTo() sendto() error: Invalid argument
> 2020-02-19 10:14:27.635 ? W/protolib: NormSession::SendMessage() sendto(224.1.2.3/4102) warning: Invalid argument
> 2020-02-19 10:14:27.638 ? E/protolib: ProtoSocket::SendTo() sendto() error: Invalid argument
> 2020-02-19 10:14:27.639 ? W/protolib: NormSession::SendMessage() sendto(224.1.2.3/4102) warning: Invalid argument
> 2020-02-19 10:14:27.642 ? E/protolib: ProtoSocket::SendTo() sendto() error: Invalid argument

Yes exactly I would benefit from a notification that the data can't be send so I can handle it in my app. Otherwise I have no idea if the data was send or not.
Yes, NORM is trying to send the data again and again. This is good. But it does it in a very fast endless loop. It would be nice if it would use some exponential back-off.

**Comment by bebopagogo** [comment]
A couple of more questions:

1) Does it recover when your wifi becomes reconnected?  Or it a permanent condition?

2) Are you running fixed data rate or with congestion control enabled?  The latter will slow down on its own ... otherwise it does regulate the rate of this issue at the fixed data rate packet interval.  If some sort of send error notification was issued, the application could reduce the data rate as it chose ...

**Comment by bebopagogo** [comment]
I just pushed updated code that extends the NORM_SEND_ERROR notification posting cases to cover the sort of error you are getting.  I have _not_ tested it for your specific issue and did not change the "polling" behavior with regards to send retry attempts ... but with the notification you can now decide what to do at the app layer

**Comment by RocketRider** [comment]
Thank you!
I will try it in the next days.

**Comment by RocketRider** [comment]
Sorry for the delay. Now I found the time to test your new version.
Now I do see the NORM_SEND_ERROR when the WiFi drops. 

Thank you for the improvement!
